// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorldWalks.Data;

#nullable disable

namespace WorldWalks.Migrations
{
    [DbContext(typeof(WorldWalksDbContext))]
    [Migration("20260617201109_Sedding_data")]
    partial class Sedding_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorldWalks.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1165848-9b75-4650-a742-ff3fbff79a61"),
                            Status = "Easy"
                        },
                        new
                        {
                            Id = new Guid("5fdc857e-016d-46f1-b069-35a6ca94595f"),
                            Status = "Medium"
                        },
                        new
                        {
                            Id = new Guid("68a7f624-b174-480a-bda6-00e6d95b1285"),
                            Status = "Hard"
                        });
                });

            modelBuilder.Entity("WorldWalks.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f3c8c11-9c5f-41db-9e4d-bd45efc78121"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://example.com/region1.jpg"
                        },
                        new
                        {
                            Id = new Guid("1a8f4cb2-41ad-44c0-8dd1-2cc14856e4bb"),
                            Code = "WLG",
                            Name = "Wellington",
                            RegionImageUrl = "https://example.com/region2.jpg"
                        },
                        new
                        {
                            Id = new Guid("e29bdc8c-b2df-48b4-9eb7-0da3e7cf5c9c"),
                            Code = "CHC",
                            Name = "Christchurch",
                            RegionImageUrl = "https://example.com/region3.jpg"
                        },
                        new
                        {
                            Id = new Guid("a5c044b6-29ea-4e20-b59e-7e7efca067d3"),
                            Code = "DND",
                            Name = "Dunedin",
                            RegionImageUrl = "https://example.com/region4.jpg"
                        },
                        new
                        {
                            Id = new Guid("bb3a9cbe-cce3-4be3-b836-94dbb54c0f7d"),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageUrl = "https://example.com/region5.jpg"
                        },
                        new
                        {
                            Id = new Guid("6fba3df7-6453-47d0-9844-9df0f08d2441"),
                            Code = "TOS",
                            Name = "Tasman",
                            RegionImageUrl = "https://example.com/region6.jpg"
                        },
                        new
                        {
                            Id = new Guid("fc0b3800-9e0a-4d4b-b165-a05a1ba1cbe5"),
                            Code = "BOP",
                            Name = "Bay of Plenty",
                            RegionImageUrl = "https://example.com/region7.jpg"
                        },
                        new
                        {
                            Id = new Guid("d84ddc36-d8cd-4737-8dee-397a093c8d06"),
                            Code = "WKO",
                            Name = "Waikato",
                            RegionImageUrl = "https://example.com/region8.jpg"
                        },
                        new
                        {
                            Id = new Guid("ad3ee423-2e06-463d-b99e-7e09bc9e6ffe"),
                            Code = "NTL",
                            Name = "Northland",
                            RegionImageUrl = "https://example.com/region9.jpg"
                        },
                        new
                        {
                            Id = new Guid("57c7a9ff-ea12-4df1-a5d1-dcd6730fb158"),
                            Code = "GIS",
                            Name = "Gisborne",
                            RegionImageUrl = "https://example.com/region10.jpg"
                        });
                });

            modelBuilder.Entity("WorldWalks.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("HikerName")
                        .HasColumnType("text");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("WorldWalks.Models.Domain.Walk", b =>
                {
                    b.HasOne("WorldWalks.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldWalks.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
